### ISSUE TITLE
rps

### ISSUE THREAD

**Issue by stebbi36** [iamthat/idream#4]
Rock, Paper, Scissors sample

This sample demonstrates use of the Facebook SDK to create and query Open Graph Actions. It consists of two views.
The first view allows the user to post Open Graph Actions to their Timeline. The second view allows the user to 
view a list of their friends who have also installed the Rock, Paper, Scissors sample app, select one of those 
friends, and retrieve a list of the actions that that friend has recently posted.

It can serve as the basis for integrating Facebook into a real-world app that has multiple types of Open Graph actions
and that allows a user to view their friends' recent app-related activity directly from within the app.

Using the Sample
Install the Facebook SDK for iOS.
Launch the RPSSample project using Xcode from the <Facebook SDK>/samples/RPSSample directory.

**Comment by stefanajons** [comment]
#facebook

**Comment by stebbi36** [comment]
<p xmlns:cc="http://creativecommons.org/ns#" >This work is licensed under <a href="http://creativecommons.org/licenses/by-nc-sa/4.0/?ref=chooser-v1" target="_blank" rel="license noopener noreferrer" style="display:inline-block;">CC BY-NC-SA 4.0<img style="height:22px!important;margin-left:3px;vertical-align:text-bottom;" src="https://mirrors.creativecommons.org/presskit/icons/cc.svg?ref=chooser-v1"><img style="height:22px!important;margin-left:3px;vertical-align:text-bottom;" src="https://mirrors.creativecommons.org/presskit/icons/by.svg?ref=chooser-v1"><img style="height:22px!important;margin-left:3px;vertical-align:text-bottom;" src="https://mirrors.creativecommons.org/presskit/icons/nc.svg?ref=chooser-v1"><img style="height:22px!important;margin-left:3px;vertical-align:text-bottom;" src="https://mirrors.creativecommons.org/presskit/icons/sa.svg?ref=chooser-v1"></a></p>
